### ISSUE TITLE
Party chat copying over to discord

### ISSUE THREAD

**Issue by Collin-M** [manuelgu/DiscordMC#12]
While using McMMO party chat, all chat sent to a private party is sent to discord as a normal message. McMMO uses the party chat toggle: `/p`, which turns 'on' or turns 'off' party chat. When party chat is turned on, you type in chat as normal and the message is only sent to other players online in your party, not global chat. These messages are being sent to discord either way.

Not a program issue, but a compatibility issue.

Also, I have commented on Issue #9, as I am also having this problem.

Running server paper spigot 1.11.2-R0.1, DiscordMC version 1.4.8, McMMO version 1.5.07

**Comment by manuelgu** [comment]
DiscordMC does not integrate with third party apps and never will unfortunately.
