### ISSUE TITLE
Chat won't work if send_game_login and send_game_logout is set to false

### ISSUE THREAD

**Issue by LordBoos** [manuelgu/DiscordMC#17]
If I turn off these options, players are not added/removed from DiscordMC.getSubscribedPlayers() on login/logout and the chat will not work for them, because isSubscribed() returns false.
`send_game_login: false`
`send_game_logout: false`
Lines below should be placed at the start of a listener method (before setting and permission check), and not at the end of it.
```
// Add player as a permissive player
DiscordMC.getSubscribedPlayers().add(event.getPlayer().getUniqueId());
```
```
// Remove player as a permissive player
DiscordMC.getSubscribedPlayers().remove(event.getPlayer().getUniqueId());
```

**Comment by manuelgu** [comment]
Feel free to submit a PR 🎉

**Comment by LordBoos** [comment]
Submited PR #18

**Comment by manuelgu** [comment]
🎉  https://github.com/manuelgu/DiscordMC/pull/18
