### ISSUE TITLE
Plugin doesn't load.

### ISSUE THREAD

**Issue by DeadWeightt** [manuelgu/DiscordMC#25]
Hey,

I recently tried to install this on my 1.11 mc server and i see that the plugin doesn't load at all and there's nothing in the logs.
I am running my server on my debian vps.

Thanks.

**Comment by manuelgu** [comment]
Are you sure you are dropping the plugin jar into the plugins folder? If there is nothing in console and the plugin does not appear in /plugins, you are doing something wrong.

**Comment by DeadWeightt** [comment]
Yeah i'm sure im dropping it into the correct folder, maybe it's something to do with some other plugin(s) maybe an incompatibility?

P.S
Sorry for late response i've been in the process of moving houses.

**Comment by manuelgu** [comment]
99% you are doing something wrong. Everyone else can get it working. Can you try on a fresh server and send me the startup log?

**Comment by DeadWeightt** [comment]
Will do.
