### ISSUE TITLE
To use DiscordMC with a bot account connected to multiple servers

### ISSUE THREAD

**Issue by book000** [manuelgu/DiscordMC#28]
Hi,
I am using DiscordMC with a bot account connected to multiple servers.
However, it will not connect to the server I want to connect. It doesn't work as I think...
I hope I can specify the connection destination in the configuration file.

I am sorry, but not good English.
I knew I could count on you.

--- Server Data ---
Spigot 1.8.8
DiscordMC 1.4.12

**Comment by manuelgu** [comment]
You are supposed to use a bot user that is only added to 1 guild, sorry.

**Comment by book000** [comment]
ok, thank you.
