### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WilliamEstrela** [manuelgu/DiscordMC#32]
![image](https://cloud.githubusercontent.com/assets/5386302/24891068/ddc7085c-1e49-11e7-99ef-7210e6ccd241.png)

**Comment by manuelgu** [comment]
What Spigot version are you using?

**Comment by WilliamEstrela** [comment]
1.11

**Comment by manuelgu** [comment]
Exact spigot version please. Please also attach a startup log

**Comment by WilliamEstrela** [comment]
![image](https://cloud.githubusercontent.com/assets/5386302/25071418/b3ec6120-228c-11e7-963f-f5fdc3e2953c.png)

**Comment by manuelgu** [comment]
> Please also attach a startup log
