### ISSUE TITLE
discordmc.chat permission not applying immediately

### ISSUE THREAD

**Issue by SuperDragonite2172** [manuelgu/DiscordMC#35]
I'm testing out the plugin and seem to have run into a minor quirk or a bug.  The discord.chat permission doesn't appear to apply until after the player leaves and rejoins the server (and maybe after a plugin reload as well).  Is this just a quirk of using a permission manager plugin or is this a bug with the plugin?

**Comment by manuelgu** [comment]
Yes, that is correct. As updating player permissions is not something that happens on the fly, a relog of the user is required for changes to take affect. This is partially due to the plugin, partially due to the permissions system
