### ISSUE TITLE
Only /discord send works

### ISSUE THREAD

**Issue by morfie78** [manuelgu/DiscordMC#38]
Hi!  First off: https://hastebin.com/fuduqeloti

From MC to Discord:
The bot sends successfully to discord when I type /discord send somechannel Hello
The bot doesn't send what people are typing into chat, however.
Only things admins say are sent to Discord.

From Discord to MC:
When people type in discord, it gets sent to the server as "(discord [channelhere]) usernamehere >> message", but no MC users actually see the message in chat.
Only admins see the messages.

We use PermissionsEX and I added the discordmc.chat permission to the main group that all users belong to. 

What should I do?
Thanks!

**Comment by manuelgu** [comment]
Have you restarted the server since adding the permission? PermissionsEx's inheritance only fully updates after a full server restart, so does DiscordMC require a server restart.

**Comment by morfie78** [comment]
No. I hot-loaded it using plugman, since users were on.  I'll restart it and see what happens.  Please stay tuned!  Thank you for the quick response!

**Comment by morfie78** [comment]
Restart worked.  Thank you!!!!
