### ISSUE TITLE
Only send global chat

### ISSUE THREAD

**Issue by morfie78** [manuelgu/DiscordMC#39]
Hi! We have three chat channels on our server. Admin, Global, and Local.  Currently, all chat gets sent to discord.  Is there a way to only have Global chat sent to discord?
Thanks.

**Comment by morfie78** [comment]
Additional info, we use [VentureChat](https://www.spigotmc.org/resources/venturechat.771/)

**Comment by manuelgu** [comment]
Unfortunately not, sorry :(
