### ISSUE TITLE
Users having to use /discord toggle before usage

### ISSUE THREAD

**Issue by linuswillner** [manuelgu/DiscordMC#9]
As it seems, for the bot to send any messages or the user be able to send anything, `discord toggle` has to be used. Before that the bot will not send messages in either direction.

Having the chat possibility be a thing per default could be nice.

**Comment by manuelgu** [comment]
Cannot reproduce. Still an issue? Please also provide a `/discord debug`

**Comment by linuswillner** [comment]
Issue seems to have been temporary. IDK what happened there.

**Comment by manuelgu** [comment]
Okay, weird! Feel free to open up another issue in case it re-appears and I will investigate further!

**Comment by Collin-M** [comment]
I am having this issue using version 1.4.8. Chat will not be sent to discord unless each user (with appropriate discordmc.chat permission node) types `/discord toggle`

**Comment by ministicraft** [comment]
I am having this issue too using version 1.4.10

**Comment by manuelgu** [comment]
@ministicraft is this also the case after the player relogs? did the player get `discordmc.chat` after the server was started with DiscordMC installed, with no restart in between?

**Comment by manuelgu** [comment]
Fixed in recent version
